theme: jekyll-theme-cayman
title: David Kivlichan
description: Machine learning engineer based in Toronto. Projects, research, resume, and creative coding sketches.
url: https://dkiv.github.io
author: David Kivlichan
